/*
Copyright 2017 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package parser

import (
	"strings"
)

// SQLNode defines the interface for all nodes
// generated by the parser.
type SQLNode interface {
	Format(buf *nodeBuffer)
}

// nodeBuffer extends strings.Builder to format SQLNode easily.
type nodeBuffer struct {
	strings.Builder
}

// Printf mimics fmt.Fprintf(buf, ...), but limited to %s for string and %v for Node.
func (buf *nodeBuffer) Printf(format string, values ...any) { _ = "STUB: not implemented"; return }

// '%'

// String returns a string representation of an SQLNode.
func String(node SQLNode) string { _ = "STUB: not implemented"; return "" }

// Statement represents a statement.
type Statement interface {
	iStatement()
	SQLNode
}

func (*Union) iStatement()          { _ = "STUB: not implemented"; return }
func (*Select) iStatement()         { _ = "STUB: not implemented"; return }
func (*Stream) iStatement()         { _ = "STUB: not implemented"; return }
func (*Insert) iStatement()         { _ = "STUB: not implemented"; return }
func (*Update) iStatement()         { _ = "STUB: not implemented"; return }
func (*Delete) iStatement()         { _ = "STUB: not implemented"; return }
func (*Set) iStatement()            { _ = "STUB: not implemented"; return }
func (*Declare) iStatement()        { _ = "STUB: not implemented"; return }
func (*Cursor) iStatement()         { _ = "STUB: not implemented"; return }
func (*BeginEnd) iStatement()       { _ = "STUB: not implemented"; return }
func (*While) iStatement()          { _ = "STUB: not implemented"; return }
func (*If) iStatement()             { _ = "STUB: not implemented"; return }
func (*DDL) iStatement()            { _ = "STUB: not implemented"; return }
func (*Show) iStatement()           { _ = "STUB: not implemented"; return }
func (*Use) iStatement()            { _ = "STUB: not implemented"; return }
func (*Begin) iStatement()          { _ = "STUB: not implemented"; return }
func (*Commit) iStatement()         { _ = "STUB: not implemented"; return }
func (*Rollback) iStatement()       { _ = "STUB: not implemented"; return }
func (*OtherRead) iStatement()      { _ = "STUB: not implemented"; return }
func (*OtherAdmin) iStatement()     { _ = "STUB: not implemented"; return }
func (*SetBoolOption) iStatement()  { _ = "STUB: not implemented"; return }
func (*MultiStatement) iStatement() { _ = "STUB: not implemented"; return }
func (*Exec) iStatement()           { _ = "STUB: not implemented"; return }
func (*Return) iStatement()         { _ = "STUB: not implemented"; return }
func (*TriggerFuncExec) iStatement() {
	_ = "STUB: not implemented"

	// ParenSelect can actually not be a top level statement,
	// but we have to allow it because it's a requirement
	// of SelectStatement.
	return
}

func (*ParenSelect) iStatement() {
	_ = "STUB: not implemented"

	// SelectStatement any SELECT statement.
	return
}

type SelectStatement interface {
	iSelectStatement()
	iStatement()
	iInsertRows()
	addOrder(*Order)
	setLimit(*Limit)
	SQLNode
}

func (*Select) iSelectStatement() { _ = "STUB: not implemented"; return }
func (*Union) iSelectStatement()  { _ = "STUB: not implemented"; return }
func (*ParenSelect) iSelectStatement() {
	_ = "STUB: not implemented"

	// Select represents a SELECT statement.
	return
}

type Select struct {
	Cache       string
	Comments    Comments
	Distinct    *DistinctClause
	Hints       string
	Top         Expr // SQL Server TOP n / TOP (n), emitted before the select list
	SelectExprs SelectExprs
	From        TableExprs
	Where       *Where
	GroupBy     GroupBy
	Having      *Where
	OrderBy     OrderBy
	Limit       *Limit
	Lock        string
	With        *With
}

// DistinctClause represents DISTINCT or DISTINCT ON (exprs) in a SELECT statement.
type DistinctClause struct {
	On Exprs // nil for plain DISTINCT, non-nil for DISTINCT ON (exprs)
}

// Format formats the node.
func (node *DistinctClause) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Select.Hints
const (
	StraightJoinHint = "straight_join "
)

// Select.Lock
const (
	ForUpdateStr = " for update"
	ShareModeStr = " lock in share mode"
)

// Select.Cache
const (
	SQLCacheStr   = "sql_cache "
	SQLNoCacheStr = "sql_no_cache "
)

// addOrder adds an order by element
func (node *Select) addOrder(order *Order) { _ = "STUB: not implemented"; return }

// setLimit sets the limit clause
func (node *Select) setLimit(limit *Limit) {
	_ = "STUB: not implemented"

	// Format formats the node.
	return
}

func (node *Select) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// addWhere adds the boolean expression to the
// WHERE clause as an AND condition. If the expression
// is an OR clause, it parenthesizes it. Currently,
// the OR operator is the only one that's lower precedence
// than AND.
func (node *Select) addWhere(expr Expr) { _ = "STUB: not implemented"; return }

// addHaving adds the boolean expression to the
// HAVING clause as an AND condition. If the expression
// is an OR clause, it parenthesizes it. Currently,
// the OR operator is the only one that's lower precedence
// than AND.
func (node *Select) addHaving(expr Expr) { _ = "STUB: not implemented"; return }

// ParenSelect is a parenthesized SELECT statement.
type ParenSelect struct {
	Select SelectStatement
}

// addOrder adds an order by element
func (node *ParenSelect) addOrder(order *Order) { _ = "STUB: not implemented"; return }

// setLimit sets the limit clause
func (node *ParenSelect) setLimit(limit *Limit) { _ = "STUB: not implemented"; return }

// Format formats the node.
func (node *ParenSelect) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Union represents a UNION statement.
type Union struct {
	Type        string
	Left, Right SelectStatement
	OrderBy     OrderBy
	Limit       *Limit
	Lock        string
	With        *With
}

// Union.Type
const (
	UnionStr         = "union"
	UnionAllStr      = "union all"
	UnionDistinctStr = "union distinct"
	IntersectStr     = "intersect"
	IntersectAllStr  = "intersect all"
	ExceptStr        = "except"
	ExceptAllStr     = "except all"
)

// addOrder adds an order by element
func (node *Union) addOrder(order *Order) { _ = "STUB: not implemented"; return }

// setLimit sets the limit clause
func (node *Union) setLimit(limit *Limit) {
	_ = "STUB: not implemented"

	// Format formats the node.
	return
}

func (node *Union) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// With represents a WITH clause (Common Table Expressions)
type With struct {
	CTEs      []*CommonTableExpr
	Recursive bool
}

// Format formats the node.
func (node *With) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// CommonTableExpr represents a single Common Table Expression in a WITH clause
type CommonTableExpr struct {
	Name       Ident
	Columns    Columns
	Definition SelectStatement
}

// Format formats the node.
func (node *CommonTableExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Stream represents a SELECT statement.
type Stream struct {
	Comments   Comments
	SelectExpr SelectExpr
	Table      TableName
}

// Format formats the node.
func (node *Stream) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Insert represents an INSERT or REPLACE statement.
// Per the MySQL docs, http://dev.mysql.com/doc/refman/5.7/en/replace.html
// Replace is the counterpart to `INSERT IGNORE`, and works exactly like a
// normal INSERT except if the row exists. In that case it first deletes
// the row and re-inserts with new values. For that reason we keep it as an Insert struct.
// Replaces are currently disallowed in sharded schemas because
// of the implications the deletion part may have on the original parser.
// If you add fields here, consider adding them to calls to validateSubquerySamePlan.
type Insert struct {
	Action     string
	Comments   Comments
	Ignore     string
	Table      TableName
	Partitions Partitions
	Columns    Columns
	Rows       InsertRows
	OnDup      OnDup
}

// DDL strings.
const (
	InsertStr  = "insert"
	ReplaceStr = "replace"
)

// Format formats the node.
func (node *Insert) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// InsertRows represents the rows for an INSERT statement.
type InsertRows interface {
	iInsertRows()
	SQLNode
}

func (*Select) iInsertRows() { _ = "STUB: not implemented"; return }
func (*Union) iInsertRows()  { _ = "STUB: not implemented"; return }
func (Values) iInsertRows()  { _ = "STUB: not implemented"; return }
func (*ParenSelect) iInsertRows() {
	_ = "STUB: not implemented"

	// Update represents an UPDATE statement.
	// If you add fields here, consider adding them to calls to validateSubquerySamePlan.
	return
}

type Update struct {
	Comments   Comments
	TableExprs TableExprs
	Exprs      UpdateExprs
	From       TableExprs
	Where      *Where
	OrderBy    OrderBy
	Limit      *Limit
}

// Format formats the node.
func (node *Update) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Delete represents a DELETE statement.
// If you add fields here, consider adding them to calls to validateSubquerySamePlan.
type Delete struct {
	Comments   Comments
	Targets    TableNames
	TableExprs TableExprs
	Partitions Partitions
	Where      *Where
	OrderBy    OrderBy
	Limit      *Limit
}

// Format formats the node.
func (node *Delete) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Set represents a SET statement.
type Set struct {
	Comments Comments
	Exprs    SetExprs
	Scope    string
}

// Set.Scope or Show.Scope
const (
	SessionStr = "session"
	GlobalStr  = "global"
)

// Format formats the node.
func (node *Set) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// DDL represents a CREATE, ALTER, DROP, RENAME or TRUNCATE statement.
// Table is set for AlterStr, DropStr, RenameStr, TruncateTable
// NewName is set for AlterStr, CreateStr, RenameStr.
// MultiStatement represents multiple statements from a single parsed statement
// (e.g., GRANT ... ON TABLE t1, t2, t3 becomes multiple DDL statements)
type MultiStatement struct {
	Statements []Statement
}

// Format formats the MultiStatement
func (node *MultiStatement) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Exec represents a EXEC statement.
type Exec struct {
	Action string // EXEC or EXECUTE
	Name   Ident
	Exprs  Exprs
}

// Format formats the Exec
func (node *Exec) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Return represents a RETURN statement.
type Return struct {
	Expr Expr
}

// Format formats the node.
func (node *Return) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type DDL struct {
	Action        DDLAction
	Table         TableName
	NewName       TableName
	IfExists      bool
	IfNotExists   bool
	TableSpec     *TableSpec
	PartitionSpec *PartitionSpec
	PartitionOf   *PartitionOfSpec // PostgreSQL PARTITION OF clause
	IndexSpec     *IndexSpec
	IndexCols     []IndexColumn
	IndexExpr     Expr
	ForeignKey    *ForeignKeyDefinition
	Exclusion     *ExclusionDefinition
	Policy        *Policy
	View          *View
	Trigger       *Trigger
	Function      *Function
	Type          *Type
	Domain        *Domain
	Comment       *Comment
	Extension     *Extension
	Schema        *Schema
	Grant         *Grant
}

// PartitionOfSpec represents PostgreSQL CREATE TABLE ... PARTITION OF syntax
type PartitionOfSpec struct {
	ParentTable TableName
	BoundSpec   *PartitionBoundSpec
}

// PartitionBoundSpec represents the partition bound (FOR VALUES ... or DEFAULT)
type PartitionBoundSpec struct {
	// For RANGE partitions: FROM (expr_list) TO (expr_list)
	From Exprs
	To   Exprs
	// For LIST partitions: IN (expr_list)
	In Exprs
	// For DEFAULT partition
	IsDefault bool
}

type DDLAction int

// DDL actions
const (
	AddForeignKey = DDLAction(iota)
	AddIndex
	AddPrimaryKey
	AddExclusion
	CommentOn
	CreateExtension
	CreateFunction
	CreateIndex
	CreatePolicy
	CreateTable
	CreateTrigger
	CreateType
	CreateView
	CreateSchema
	CreateDomain
	GrantPrivilege
	RevokePrivilege
	DropIndex
	DropExtension
	DropPolicy
)

// View types
const (
	ViewStr             = "view"
	MaterializedViewStr = "materialized view"
	SqlSecurityStr      = "sql security"
)

// Format formats the node.
func (node *DDL) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Format formats the PartitionBoundSpec node.
func (node *PartitionBoundSpec) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Partition strings
const (
	ReorganizeStr = "reorganize partition"
)

// PartitionSpec describe partition actions (for alter and create)
type PartitionSpec struct {
	Action      string
	Name        Ident
	Definitions []*PartitionDefinition
}

// Format formats the node.
func (node *PartitionSpec) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// PartitionDefinition describes a partition definition for RANGE or LIST partitions
type PartitionDefinition struct {
	Name     Ident
	Limit    Expr  // For single-value LESS THAN (legacy)
	LessThan Exprs // For RANGE: VALUES LESS THAN (expr_list)
	In       Exprs // For LIST: VALUES IN (expr_list)
	Maxvalue bool  // For LESS THAN MAXVALUE
}

// Format formats the node
func (node *PartitionDefinition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TablePartition represents PARTITION BY clause for MySQL/MariaDB
type TablePartition struct {
	Type        string                 // RANGE, RANGE COLUMNS, LIST, LIST COLUMNS, HASH, LINEAR HASH, KEY, LINEAR KEY
	Columns     []Ident                // For RANGE COLUMNS, LIST COLUMNS, KEY (column names)
	Expr        Exprs                  // For RANGE, LIST, HASH (expression list)
	Partitions  int                    // For PARTITIONS n (0 if not specified)
	Definitions []*PartitionDefinition // Individual partition definitions
}

// Format formats the node
func (p *TablePartition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// RANGE COLUMNS, LIST COLUMNS, KEY

// RANGE, LIST, HASH

// TableSpec describes the structure of a table from a CREATE TABLE statement
type TableSpec struct {
	Columns     []*ColumnDefinition
	Indexes     []*IndexDefinition
	ForeignKeys []*ForeignKeyDefinition
	Checks      []*CheckDefinition
	Exclusions  []*ExclusionDefinition // for Postgres
	Options     map[string]string
	Partition   *TablePartition // Partition definition (MySQL/MariaDB)
}

// Format formats the node.
func (ts *TableSpec) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// addColumn appends the given column to the list in the spec
func (ts *TableSpec) addColumn(cd *ColumnDefinition) { _ = "STUB: not implemented"; return }

// addIndex appends the given index to the list in the spec
func (ts *TableSpec) addIndex(id *IndexDefinition) { _ = "STUB: not implemented"; return }

func (ts *TableSpec) addCheck(check *CheckDefinition) { _ = "STUB: not implemented"; return }

func (ts *TableSpec) addForeignKey(foreignKey *ForeignKeyDefinition) {
	_ = "STUB: not implemented"
	return
}

func (ts *TableSpec) addExclusion(exclusion *ExclusionDefinition) {
	_ = "STUB: not implemented"
	return
}

// ColumnDefinition describes a column in a CREATE TABLE statement
type ColumnDefinition struct {
	Name          Ident
	Type          ColumnType
	InlineComment []byte // For inline comments like -- @renamed from=oldname
}

// Format formats the node.
func (col *ColumnDefinition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type Sequence struct {
	Name        string
	IfNotExists bool
	Type        string

	IncrementBy *SQLVal
	MinValue    *SQLVal
	NoMinValue  *BoolVal
	MaxValue    *SQLVal
	NoMaxValue  *BoolVal
	StartWith   *SQLVal
	Cache       *SQLVal
	Cycle       *BoolVal
	NoCycle     *BoolVal
	OwnedBy     string
}

type GeneratedColumn struct {
	Expr          Expr
	GeneratedType string
}

type IdentityOpt struct {
	Behavior          string
	Sequence          *Sequence
	NotForReplication bool
}

// ColumnType represents a sql type in a CREATE TABLE statement
// All optional fields are nil if not specified
type ColumnType struct {
	// The base type string
	Type string
	// TypeIdent stores the original identifier with quote information for custom types (e.g., domains).
	// When TypeIdent is set (i.e., not zero value), use TypeIdent.Quoted to determine quoting.
	TypeIdent Ident

	// Generic field options.
	NotNull             *BoolVal
	Autoincrement       BoolVal
	AutoRandom          BoolVal
	AutoRandomShardBits int
	AutoRandomRange     int
	Default             *DefaultDefinition
	Srid                *SridDefinition
	OnUpdate            *SQLVal
	Comment             *SQLVal
	Check               *CheckDefinition
	Array               BoolVal

	// Numeric field options
	Length       *SQLVal
	Unsigned     BoolVal
	Zerofill     BoolVal
	Scale        *SQLVal
	DisplayWidth *SQLVal

	// Text field options
	Charset string
	Collate string

	// Timestamp field options
	Timezone BoolVal

	// Enum values
	EnumValues []string

	// Key specification
	KeyOpt ColumnKeyOption

	References            TableName
	ReferenceNames        Columns
	ReferenceMatch        Ident // for Postgres: MATCH FULL, MATCH PARTIAL, MATCH SIMPLE
	ReferenceOnDelete     Ident
	ReferenceOnUpdate     Ident
	ReferenceDeferrable   *BoolVal // for Postgres: DEFERRABLE, NOT DEFERRABLE, or nil
	ReferenceInitDeferred *BoolVal // for Postgres: INITIALLY DEFERRED, INITIALLY IMMEDIATE, or nil

	// MySQL: GENERATED ALWAYS AS (expr)
	Generated *GeneratedColumn

	// PostgreSQL: GENERATED AS IDENTITY
	Identity *IdentityOpt
}

type DefaultDefinition struct {
	Expression     DefaultExpression
	ConstraintName Ident // only for MSSQL
}

type DefaultExpression struct {
	Expr Expr
}

type SridDefinition struct {
	Value *SQLVal
}

type CheckDefinition struct {
	Where             Where
	ConstraintName    Ident
	NotForReplication bool
	NoInherit         BoolVal
}

type ExclusionPair struct {
	Expression Expr
	Operator   string
}

type ExclusionDefinition struct {
	ConstraintName Ident
	IndexType      Ident
	Exclusions     []ExclusionPair
	Where          *Where
}

// Format returns a canonical string representation of the type and all relevant options
func (ct *ColumnType) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IndexDefinition describes an index in a CREATE TABLE statement
type IndexDefinition struct {
	Info              *IndexInfo
	Columns           []IndexColumn
	Options           []*IndexOption
	Partition         *IndexPartition
	ConstraintOptions *ConstraintOptions
}

// Format formats the node.
func (idx *IndexDefinition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IndexInfo describes the name and type of an index in a CREATE TABLE statement
type IndexInfo struct {
	Type      string
	Name      Ident
	Primary   bool
	Spatial   bool
	Unique    bool
	Fulltext  bool
	Vector    bool
	Clustered BoolVal
}

// Format formats the node.
func (ii *IndexInfo) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type IndexColumnsOrExpression struct {
	IndexCols []IndexColumn
	IndexExpr Expr
}

// IndexColumn describes a column in an index definition with optional length
type IndexColumn struct {
	Column        Ident
	Length        *SQLVal
	Direction     string
	NullsOrdering string // "first" or "last" for NULLS FIRST/LAST
	Collation     string // Collation name for COLLATE
	OperatorClass string
	Expression    Expr // For functional indexes like ((CASE WHEN ...))

	WithoutOverlaps bool // For PostgreSQL 18+ temporal PRIMARY KEY / UNIQUE constraints
}

func (ic IndexColumn) String() string { _ = "STUB: not implemented"; return "" }

// LengthScaleOption is used for types that have an optional length
// and scale
type LengthScaleOption struct {
	Length *SQLVal
	Scale  *SQLVal
}

// IndexOption is used for trailing options for indexes: COMMENT, KEY_BLOCK_SIZE, USING
type IndexOption struct {
	Name  string
	Value *SQLVal
}

type IndexPartition struct {
	Name   string
	Column string
}

// ColumnKeyOption indicates whether or not the given column is defined as an
// index element and contains the type of the option
type ColumnKeyOption int

const (
	colKeyNone ColumnKeyOption = iota
	colKeyPrimary
	colKeySpatialKey
	colKeyUnique
	colKeyUniqueKey
	colKey
)

type IndexSpec struct {
	Name              Ident
	Type              Ident
	Unique            bool
	Primary           bool
	Vector            bool // for MariaDB vector indexes
	Constraint        bool
	Async             bool // for Aurora DSQL
	Concurrently      bool // for PostgreSQL
	NullsNotDistinct  bool // for PostgreSQL 15+ UNIQUE indexes
	Clustered         bool // for MSSQL
	ColumnStore       bool // for MSSQL
	Included          []Ident
	Where             *Where
	Options           []*IndexOption
	Partition         *IndexPartition // for MSSQL
	ConstraintOptions *ConstraintOptions
}

type ConstraintOptions struct {
	Deferrable        bool // for Postgres
	InitiallyDeferred bool // for Postgres
}

type ForeignKeyDefinition struct {
	ConstraintName    Ident
	IndexName         Ident
	IndexColumns      []Ident
	ReferenceName     TableName
	ReferenceColumns  []Ident
	Match             Ident // for Postgres: MATCH FULL, MATCH PARTIAL, MATCH SIMPLE
	OnDelete          Ident
	OnUpdate          Ident
	NotForReplication bool
	ConstraintOptions *ConstraintOptions
	Period            bool // For PostgreSQL 18+ temporal FOREIGN KEY constraints (PERIOD on last column)
}

type Policy struct {
	Name       Ident
	Permissive Permissive
	Scope      string
	To         []Ident
	Using      *Where
	WithCheck  *Where
}

type Extension struct {
	Name Ident
}

type Schema struct {
	Name string
}

type Grant struct {
	IsGrant         bool     // true for GRANT, false for REVOKE
	Privileges      []string // e.g., ["SELECT", "INSERT", "UPDATE"]
	TableName       TableName
	Grantees        []string
	WithGrantOption bool // Not supported - parser will error if WITH GRANT OPTION is used
	CascadeOption   bool // Not supported - parser will error if CASCADE/RESTRICT is used
}

type Permissive string

// Show represents a show statement.
type Show struct {
	Type          string
	OnTable       TableName
	ShowTablesOpt *ShowTablesOpt
	Scope         string
}

// Format formats the node.
func (node *Show) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ShowTablesOpt is show tables option
type ShowTablesOpt struct {
	Extended string
	Full     string
	DbName   string
	Filter   *ShowFilter
}

// ShowFilter is show tables filter
type ShowFilter struct {
	Like   string
	Filter Expr
}

// Format formats the node.
func (node *ShowFilter) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Use represents a use statement.
type Use struct {
	DBName Ident
}

// Format formats the node.
func (node *Use) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Begin represents a Begin statement.
type Begin struct{}

// Format formats the node.
func (node *Begin) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Commit represents a Commit statement.
type Commit struct{}

// Format formats the node.
func (node *Commit) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Rollback represents a Rollback statement.
type Rollback struct{}

// Format formats the node.
func (node *Rollback) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OtherRead represents a DESCRIBE, or EXPLAIN statement.
// It should be used only as an indicator. It does not contain
// the full AST for the statement.
type OtherRead struct{}

// Format formats the node.
func (node *OtherRead) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OtherAdmin represents a misc statement that relies on ADMIN privileges,
// such as REPAIR, OPTIMIZE, or TRUNCATE statement.
// It should be used only as an indicator. It does not contain
// the full AST for the statement.
type OtherAdmin struct{}

// Format formats the node.
func (node *OtherAdmin) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SetOption represents a SET statement that specifies option in SQL Server.
type SetBoolOption struct {
	OptionNames []string
	Value       *SQLVal
}

// Format formats the node.
func (node *SetBoolOption) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Comments represents a list of comments.
type Comments []string

// Format formats the node.
func (node Comments) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type View struct {
	Type         string
	SecurityType string
	Name         TableName
	Definition   SelectStatement
	WithData     bool // true for "WITH DATA"
	WithNoData   bool // true for "WITH NO DATA"
}

// TriggerEvent represents a single trigger event (INSERT, UPDATE, DELETE, or UPDATE OF columns)
type TriggerEvent struct {
	Type    string  // "INSERT", "UPDATE", "DELETE"
	Columns Columns // For UPDATE OF col1, col2 - nil for INSERT/DELETE/plain UPDATE
}

type Trigger struct {
	Name      *ColName
	TableName TableName
	Time      string
	Event     []TriggerEvent
	When      Expr
	Body      []Statement
}

// TriggerFuncExec represents PostgreSQL's EXECUTE FUNCTION/PROCEDURE in triggers
type TriggerFuncExec struct {
	Keyword  string // "FUNCTION" or "PROCEDURE"
	FuncName ObjectName
	Args     Exprs
}

func (node *TriggerFuncExec) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Function represents a PostgreSQL CREATE FUNCTION statement
type Function struct {
	Name       ObjectName
	Args       []FunctionArg
	ReturnType string
	Body       string   // The function body (dollar-quoted string content)
	Language   string   // e.g., "plpgsql", "sql"
	OrReplace  bool     // true if CREATE OR REPLACE FUNCTION
	Options    []string // Additional options like VOLATILE, IMMUTABLE, etc.
}

// FunctionArg represents a function argument
type FunctionArg struct {
	Mode    string // IN, OUT, INOUT, VARIADIC (optional)
	Name    Ident
	Type    string
	Default Expr
}

type Type struct {
	Name       ObjectName
	Type       ColumnType
	EnumValues []string
}

type Domain struct {
	Name        ObjectName
	DataType    ColumnType // the underlying data type for the domain
	Default     *DefaultDefinition
	NotNull     bool
	Collation   string
	Constraints []*CheckDefinition // PostgreSQL allows multiple CHECK constraints
}

type Comment struct {
	ObjectType   string
	Object       []Ident // Parts of the object name: [schema, table] or [schema, table, column]
	Comment      string
	FunctionArgs []FunctionArg // For COMMENT ON FUNCTION, stores the function signature
}

// SelectExprs represents SELECT expressions.
type SelectExprs []SelectExpr

// Format formats the node.
func (node SelectExprs) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SelectExprsToExprs converts SelectExprs to Exprs by extracting the Expr from each AliasedExpr.
func SelectExprsToExprs(selectExprs SelectExprs) Exprs {
	_ = "STUB: not implemented"
	return *new(Exprs)
}

// SelectExpr represents a SELECT expression.
type SelectExpr interface {
	iSelectExpr()
	SQLNode
}

func (*StarExpr) iSelectExpr() { _ = "STUB: not implemented"; return }
func (*AliasedExpr) iSelectExpr() {
	_ = "STUB: not implemented"

	// StarExpr defines a '*' or 'table.*' expression.
	return
}

type StarExpr struct {
	TableName TableName
}

// Format formats the node.
func (node *StarExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// AliasedExpr defines an aliased SELECT expression.
type AliasedExpr struct {
	Expr Expr
	As   Ident
}

// Format formats the node.
func (node *AliasedExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Columns represents an insert column list.
type Columns []Ident

// Format formats the node.
func (node Columns) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Partitions is a type alias for Columns so we can handle printing efficiently
type Partitions Columns

// Format formats the node
func (node Partitions) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TableExprs represents a list of table expressions.
type TableExprs []TableExpr

// Format formats the node.
func (node TableExprs) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IsEmpty returns true if there are no table expressions.
func (node TableExprs) IsEmpty() bool { _ = "STUB: not implemented"; return false }

// TableExpr represents a table expression.
type TableExpr interface {
	iTableExpr()
	SQLNode
}

func (*AliasedTableExpr) iTableExpr() { _ = "STUB: not implemented"; return }
func (*ParenTableExpr) iTableExpr()   { _ = "STUB: not implemented"; return }
func (*JoinTableExpr) iTableExpr() {
	_ = "STUB: not implemented"

	// AliasedTableExpr represents a table expression
	// coupled with an optional alias or index hint.
	// If As is empty, no alias was used.
	return
}

type AliasedTableExpr struct {
	Expr       SimpleTableExpr
	Partitions Partitions
	As         Ident
	Columns    Columns
	TableHints []string
	IndexHints *IndexHints
}

// Format formats the node.
func (node *AliasedTableExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Hint node provides the space padding.

// SimpleTableExpr represents a simple table expression.
type SimpleTableExpr interface {
	iSimpleTableExpr()
	SQLNode
}

func (TableName) iSimpleTableExpr()          { _ = "STUB: not implemented"; return }
func (*Subquery) iSimpleTableExpr()          { _ = "STUB: not implemented"; return }
func (*FuncExpr) iSimpleTableExpr()          { _ = "STUB: not implemented"; return }
func (*OpenJSONTableExpr) iSimpleTableExpr() { _ = "STUB: not implemented"; return }
func (Values) iSimpleTableExpr() {
	_ = "STUB: not implemented"

	// OpenJSONTableExpr represents a SQL Server OPENJSON table expression.
	return
}

type OpenJSONTableExpr struct {
	Exprs SelectExprs
	With  OpenJSONSchema
}

func (node *OpenJSONTableExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OpenJSONSchema represents the OPENJSON WITH column schema.
type OpenJSONSchema []*OpenJSONSchemaItem

func (node OpenJSONSchema) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OpenJSONSchemaItem represents a single OPENJSON WITH column definition.
type OpenJSONSchemaItem struct {
	Name   Ident
	Type   ColumnType
	Path   string
	AsJSON bool
}

func (node *OpenJSONSchemaItem) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TableNames is a list of TableName.
type TableNames []TableName

// Format formats the node.
func (node TableNames) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TableName represents a table name: [Name] or [Schema].[Name]
type TableName struct {
	Schema Ident
	Name   Ident
}

// Format formats the node.
func (node TableName) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IsEmpty returns true if TableName is nil or empty.
func (node TableName) IsEmpty() bool {
	_ = "STUB: not implemented"
	// If Name is empty, Schema is also empty.
	return false
}

// toViewName returns a TableName acceptable for use as a VIEW.
// For quoted identifiers, case is preserved (PostgreSQL behavior).
// For unquoted identifiers, the name is lowercased (PostgreSQL normalizes to lowercase).
// Schema is left untouched as databases are case-sensitive for schemas.
func (node TableName) toViewName() TableName {
	_ = "STUB: not implemented"
	return *

	// Only lowercase unquoted identifiers; quoted identifiers preserve their case
	new(TableName)
}

// ObjectName represents a schema-qualified database object name: [Name] or [Schema].[Name]
// This is used for objects like domains, types, functions, etc. that can be schema-qualified
// but are not tables.
type ObjectName struct {
	Schema Ident
	Name   Ident
}

// Format formats the node.
func (node ObjectName) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ParenTableExpr represents a parenthesized list of TableExpr.
type ParenTableExpr struct {
	Exprs TableExprs
}

// Format formats the node.
func (node *ParenTableExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// JoinCondition represents the join conditions (either a ON or USING clause)
// of a JoinTableExpr.
type JoinCondition struct {
	On    Expr
	Using Columns
}

// Format formats the node.
func (node JoinCondition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// JoinTableExpr represents a TableExpr that's a JOIN operation.
type JoinTableExpr struct {
	LeftExpr  TableExpr
	Join      string
	RightExpr TableExpr
	Condition JoinCondition
}

// JoinTableExpr.Join
const (
	JoinStr             = "join"
	StraightJoinStr     = "straight_join"
	LeftJoinStr         = "left join"
	RightJoinStr        = "right join"
	NaturalJoinStr      = "natural join"
	NaturalLeftJoinStr  = "natural left join"
	NaturalRightJoinStr = "natural right join"
	CrossJoinStr        = "cross join"
	CrossApplyStr       = "cross apply"
	OuterApplyStr       = "outer apply"
)

// Format formats the node.
func (node *JoinTableExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IndexHints represents a list of index hints.
type IndexHints struct {
	Type    string
	Indexes []Ident
}

// Index hints.
const (
	UseStr    = "use "
	IgnoreStr = "ignore "
	ForceStr  = "force "
)

// Format formats the node.
func (node *IndexHints) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Where represents a WHERE or HAVING clause.
type Where struct {
	Type string
	Expr Expr
}

// Where.Type
const (
	WhereStr  = "where"
	HavingStr = "having"
)

// NewWhere creates a WHERE or HAVING clause out
// of a Expr. If the expression is nil, it returns nil.
func NewWhere(typ string, expr Expr) *Where { _ = "STUB: not implemented"; return nil }

// Format formats the node.
func (node *Where) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Expr represents an expression.
type Expr interface {
	iExpr()
	SQLNode
}

func (*AndExpr) iExpr()             { _ = "STUB: not implemented"; return }
func (*OrExpr) iExpr()              { _ = "STUB: not implemented"; return }
func (*NotExpr) iExpr()             { _ = "STUB: not implemented"; return }
func (*ParenExpr) iExpr()           { _ = "STUB: not implemented"; return }
func (*ComparisonExpr) iExpr()      { _ = "STUB: not implemented"; return }
func (*RangeCond) iExpr()           { _ = "STUB: not implemented"; return }
func (*IsExpr) iExpr()              { _ = "STUB: not implemented"; return }
func (*ExistsExpr) iExpr()          { _ = "STUB: not implemented"; return }
func (*SQLVal) iExpr()              { _ = "STUB: not implemented"; return }
func (*NullVal) iExpr()             { _ = "STUB: not implemented"; return }
func (BoolVal) iExpr()              { _ = "STUB: not implemented"; return }
func (*ColName) iExpr()             { _ = "STUB: not implemented"; return }
func (*NewQualifierColName) iExpr() { _ = "STUB: not implemented"; return }
func (ValTuple) iExpr()             { _ = "STUB: not implemented"; return }
func (*Subquery) iExpr()            { _ = "STUB: not implemented"; return }
func (ListArg) iExpr()              { _ = "STUB: not implemented"; return }
func (*BinaryExpr) iExpr()          { _ = "STUB: not implemented"; return }
func (*UnaryExpr) iExpr()           { _ = "STUB: not implemented"; return }
func (*IntervalExpr) iExpr()        { _ = "STUB: not implemented"; return }
func (*TypedLiteral) iExpr()        { _ = "STUB: not implemented"; return }
func (*CollateExpr) iExpr()         { _ = "STUB: not implemented"; return }
func (*FuncExpr) iExpr()            { _ = "STUB: not implemented"; return }
func (*CaseExpr) iExpr()            { _ = "STUB: not implemented"; return }
func (*ValuesFuncExpr) iExpr()      { _ = "STUB: not implemented"; return }
func (*UpdateFuncExpr) iExpr()      { _ = "STUB: not implemented"; return }
func (*CastExpr) iExpr()            { _ = "STUB: not implemented"; return }
func (*ConvertExpr) iExpr()         { _ = "STUB: not implemented"; return }
func (*SubstrExpr) iExpr()          { _ = "STUB: not implemented"; return }
func (*ExtractExpr) iExpr()         { _ = "STUB: not implemented"; return }
func (*ConvertUsingExpr) iExpr()    { _ = "STUB: not implemented"; return }
func (*MatchExpr) iExpr()           { _ = "STUB: not implemented"; return }
func (*GroupConcatExpr) iExpr()     { _ = "STUB: not implemented"; return }
func (*TrimExpr) iExpr()            { _ = "STUB: not implemented"; return }
func (*MethodCallExpr) iExpr()      { _ = "STUB: not implemented"; return }
func (*OverExpr) iExpr()            { _ = "STUB: not implemented"; return }
func (*Default) iExpr()             { _ = "STUB: not implemented"; return }
func (*ArrayConstructor) iExpr()    { _ = "STUB: not implemented"; return }
func (*FuncCallExpr) iExpr()        { _ = "STUB: not implemented"; return }
func (*NextSeqValExpr) iExpr()      { _ = "STUB: not implemented"; return }
func (*SuffixExpr) iExpr() {
	_ = "STUB: not implemented"

	// Exprs represents a list of value expressions.
	// It's not a valid expression because it's not parenthesized.
	return
}

type Exprs []Expr

// Format formats the node.
func (node Exprs) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// AndExpr represents an AND expression.
type AndExpr struct {
	Left, Right Expr
}

// Format formats the node.
func (node *AndExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OrExpr represents an OR expression.
type OrExpr struct {
	Left, Right Expr
}

// Format formats the node.
func (node *OrExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// NotExpr represents a NOT expression.
type NotExpr struct {
	Expr Expr
}

// Format formats the node.
func (node *NotExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ParenExpr represents a parenthesized boolean expression.
type ParenExpr struct {
	Expr Expr
}

// Format formats the node.
func (node *ParenExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ComparisonExpr represents a two-value comparison expression.
type ComparisonExpr struct {
	Operator    string
	Left, Right Expr
	Escape      Expr
	All, Any    bool
}

// ComparisonExpr.Operator
const (
	EqualStr             = "="
	LessThanStr          = "<"
	GreaterThanStr       = ">"
	LessEqualStr         = "<="
	GreaterEqualStr      = ">="
	NotEqualStr          = "!="
	NullSafeEqualStr     = "<=>"
	InStr                = "in"
	NotInStr             = "not in"
	LikeStr              = "like"
	NotLikeStr           = "not like"
	ILikeStr             = "ilike"
	NotILikeStr          = "not ilike"
	RegexpStr            = "regexp"
	NotRegexpStr         = "not regexp"
	JSONExtractOp        = "->"
	JSONUnquoteExtractOp = "->>"
	PosixRegexStr        = "~"
	PosixRegexCiStr      = "~*"
	PosixNotRegexStr     = "!~"
	PosixNotRegexCiStr   = "!~*"
	IsDistinctFromStr    = "is distinct from"
	IsNotDistinctFromStr = "is not distinct from"
	OverlapsStr          = "overlaps"
)

// Format formats the node.
func (node *ComparisonExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// For ALL/ANY/SOME, wrap the right expression in parentheses if it's not already a ParenExpr or Subquery

// RangeCond represents a BETWEEN or a NOT BETWEEN expression.
type RangeCond struct {
	Operator string
	Left     Expr
	From, To Expr
}

// RangeCond.Operator
const (
	BetweenStr    = "between"
	NotBetweenStr = "not between"
)

// Format formats the node.
func (node *RangeCond) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IsExpr represents an IS ... or an IS NOT ... expression.
type IsExpr struct {
	Operator string
	Expr     Expr
}

// IsExpr.Operator
const (
	IsNullStr       = "is null"
	IsNotNullStr    = "is not null"
	IsTrueStr       = "is true"
	IsNotTrueStr    = "is not true"
	IsFalseStr      = "is false"
	IsNotFalseStr   = "is not false"
	IsUnknownStr    = "is unknown"
	IsNotUnknownStr = "is not unknown"
)

// Format formats the node.
func (node *IsExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ExistsExpr represents an EXISTS expression.
type ExistsExpr struct {
	Subquery *Subquery
}

// Format formats the node.
func (node *ExistsExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ValType specifies the type for SQLVal.
type ValType int

// These are the possible Valtype values.
// HexNum represents a 0x... value. It cannot
// be treated as a simple value because it can
// be interpreted differently depending on the
// context.
const (
	StrVal = ValType(iota)
	IntVal
	FloatVal
	HexNum
	HexVal
	ValArg
	BitVal
	ValBool
	UnicodeStrVal
)

// SQLVal represents a single value.
type SQLVal struct {
	Type ValType
	Val  string
}

// NewStrVal builds a new StrVal.
func NewStrVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewIntVal builds a new IntVal.
func NewIntVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewFloatVal builds a new FloatVal.
func NewFloatVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewHexNum builds a new HexNum.
func NewHexNum(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewHexVal builds a new HexVal.
func NewHexVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewBitVal builds a new BitVal containing a bit literal.
func NewBitVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewValArg builds a new ValArg.
func NewValArg(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

func NewBoolSQLVal(in bool) *SQLVal { _ = "STUB: not implemented"; return nil }

// NewUnicode builds a new UnicodeStrVal.
func NewUnicodeStrVal(in string) *SQLVal { _ = "STUB: not implemented"; return nil }

func NewValArgWithOpt(in string, opt *SQLVal) *SQLVal { _ = "STUB: not implemented"; return nil }

// Format formats the node.
func (node *SQLVal) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

func encodeSQLBytes(val string, buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// NullVal represents a NULL value.
type NullVal struct{}

// Format formats the node.
func (node *NullVal) Format(buf *nodeBuffer) {
	_ = "STUB: not implemented"

	// BoolVal is true or false.
	return
}

type BoolVal bool

func NewBoolVal(flag bool) *BoolVal { _ = "STUB: not implemented"; return nil }

// Format formats the node.
func (node BoolVal) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ColName represents a column name.
type ColName struct {
	// Metadata is not populated by the parser.
	// It's a placeholder for analyzers to store
	// additional data, typically info about which
	// table or column this node references.
	Metadata  any
	Name      Ident
	Qualifier TableName
}

// Format formats the node.
func (node *ColName) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// NewQualifierColName represents a column name with NEW qualifier.
type NewQualifierColName struct {
	Name Ident
}

// Format formats the node.
func (node *NewQualifierColName) Format(buf *nodeBuffer) {
	_ = "STUB: not implemented"
	// We don't have to backtick NEW qualifier.
	return
}

// ColTuple represents a list of column values.
// It can be ValTuple, Subquery, ListArg.
type ColTuple interface {
	iColTuple()
	Expr
}

func (ValTuple) iColTuple()  { _ = "STUB: not implemented"; return }
func (*Subquery) iColTuple() { _ = "STUB: not implemented"; return }
func (ListArg) iColTuple() {
	_ = "STUB: not implemented"

	// ValTuple represents a tuple of actual values.
	return
}

type ValTuple Exprs

// Format formats the node.
func (node ValTuple) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Subquery represents a subquery.
type Subquery struct {
	Select SelectStatement
}

// Format formats the node.
func (node *Subquery) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ListArg represents a named list argument.
type ListArg []byte

// Format formats the node.
func (node ListArg) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// BinaryExpr represents a binary value expression.
type BinaryExpr struct {
	Operator    string
	Left, Right Expr
}

// BinaryExpr.Operator
const (
	BitAndStr     = "&"
	BitOrStr      = "|"
	BitXorStr     = "^"
	PlusStr       = "+"
	MinusStr      = "-"
	MultStr       = "*"
	DivStr        = "/"
	IntDivStr     = "div"
	ModStr        = "%"
	ShiftLeftStr  = "<<"
	ShiftRightStr = ">>"
)

// Format formats the node.
func (node *BinaryExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// UnaryExpr represents a unary value expression.
type UnaryExpr struct {
	Operator string
	Expr     Expr
}

// UnaryExpr.Operator
const (
	UPlusStr   = "+"
	UMinusStr  = "-"
	TildaStr   = "~"
	BangStr    = "!"
	BinaryStr  = "binary "
	UBinaryStr = "_binary "
)

// Format formats the node.
func (node *UnaryExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// IntervalExpr represents a date-time INTERVAL expression.
type IntervalExpr struct {
	Expr Expr
	Unit string
}

// Format formats the node.
func (node *IntervalExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TypedLiteral represents a typed literal like DATE '2022-01-01' or TIMESTAMP '2022-01-01'.
type TypedLiteral struct {
	Type  string
	Value Expr
}

// Format formats the node.
func (node *TypedLiteral) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// CollateExpr represents dynamic collate operator.
type CollateExpr struct {
	Expr    Expr
	Charset string
}

// Format formats the node.
func (node *CollateExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// FuncExpr represents a function call that takes SelectExprs.
type FuncExpr struct {
	Qualifier   Ident
	Name        Ident
	Distinct    bool
	Exprs       SelectExprs
	WithinGroup OrderBy
	Over        *OverExpr
}

// Format formats the node.
func (node *FuncExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Function names should not be back-quoted even
// if they match a reserved word. So, print the
// name as is.

// FuncCallExpr represents a function call that takes Exprs.
type FuncCallExpr struct {
	Name  Ident
	Exprs Exprs
}

func (node *FuncCallExpr) Format(buf *nodeBuffer) {
	_ = "STUB: not implemented"
	// Function names should not be back-quoted even
	// if they match a reserved word. So, print the
	// name as is.
	return
}

// GroupConcatExpr represents a call to GROUP_CONCAT
type GroupConcatExpr struct {
	Distinct  string
	Exprs     SelectExprs
	OrderBy   OrderBy
	Separator string
}

// Format formats the node
func (node *GroupConcatExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OverExpr represents a call to OVER
type OverExpr struct {
	PartitionBy PartitionBy
	OrderBy     OrderBy
}

// Format formats the node
func (node *OverExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ValuesFuncExpr represents a function call.
type ValuesFuncExpr struct {
	Name *ColName
}

// Format formats the node.
func (node *ValuesFuncExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// UpdateFuncExpr represents a function call.
type UpdateFuncExpr struct {
	Name *ColName
}

// Format formats the node.
func (node *UpdateFuncExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SubstrExpr represents a call to SubstrExpr(column, value_expression) or SubstrExpr(column, value_expression,value_expression)
// also supported syntax SubstrExpr(column from value_expression for value_expression)
type SubstrExpr struct {
	Name SelectExpr
	From Expr
	To   Expr
}

// Format formats the node.
func (node *SubstrExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// TrimExpr represents a TRIM expression.
type TrimExpr struct {
	TrimChar Expr
	String   Expr
}

// Format formats the node.
func (node *TrimExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// MethodCallExpr represents a SQL Server method call on an expression.
type MethodCallExpr struct {
	Receiver Expr
	Name     Ident
	Exprs    Exprs
}

func (node *MethodCallExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ExtractExpr represents EXTRACT(field FROM source)
type ExtractExpr struct {
	Field  string
	Source Expr
}

// Format formats the node.
func (node *ExtractExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// CastExpr represents expr::type
type CastExpr struct {
	Expr Expr
	Type *ConvertType
}

func (node *CastExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Convert types
const (
	CastStr    = "cast"
	TryCastStr = "try_cast"
	Type1stStr = "type1st"
)

// ConvertExpr represents a call to CONVERT(expr, type) and CAST(expr AS type)
// or CONVERT(type, expr[, style]).
type ConvertExpr struct {
	Action string
	Expr   Expr
	Type   *ConvertType
	Style  Expr
}

func (node *ConvertExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ConvertUsingExpr represents a call to CONVERT(expr USING charset).
type ConvertUsingExpr struct {
	Expr Expr
	Type string
}

func (node *ConvertUsingExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// ConvertType represents the type in call to CONVERT(expr, type)
type ConvertType struct {
	Type     string
	Length   *SQLVal
	Scale    *SQLVal
	Operator string
	Charset  string
}

// this string is "character set" and this comment is required
const (
	CharacterSetStr = " character set"
)

// Format formats the node.
func (node *ConvertType) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// MatchExpr represents a call to the MATCH function
type MatchExpr struct {
	Columns SelectExprs
	Expr    Expr
	Option  string
}

// MatchExpr.Option
const (
	BooleanModeStr                           = " in boolean mode"
	NaturalLanguageModeStr                   = " in natural language mode"
	NaturalLanguageModeWithQueryExpansionStr = " in natural language mode with query expansion"
	QueryExpansionStr                        = " with query expansion"
)

// Format formats the node
func (node *MatchExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// CaseExpr represents a CASE expression.
type CaseExpr struct {
	Expr  Expr
	Whens []*When
	Else  Expr
}

// Format formats the node.
func (node *CaseExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Default represents a DEFAULT expression.
type Default struct {
	ColName string
}

// Format formats the node.
func (node *Default) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// NextSeqVal represents a NEXT VALUE FOR expression in SQL Server.
type NextSeqValExpr struct {
	SequenceName Ident
}

// Format formats the node.
func (node *NextSeqValExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// When represents a WHEN sub-expression.
type When struct {
	Cond Expr
	Val  Expr
}

// Format formats the node.
func (node *When) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// GroupBy represents a GROUP BY clause.
type GroupBy []Expr

// Format formats the node.
func (node GroupBy) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// OrderBy represents an ORDER By clause.
type OrderBy []*Order

// Format formats the node.
func (node OrderBy) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Order represents an ordering expression.
type Order struct {
	Expr      Expr
	Direction string
}

// Order.Direction and IndexColumn.Direction
const (
	AscScr  = "asc"
	DescScr = "desc"
)

// IndexColumn.NullsOrdering
const (
	NullsFirst = "first"
	NullsLast  = "last"
)

// Format formats the node.
func (node *Order) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// PartitionBy represents a PARTITION BY clause.
type PartitionBy []*Partition

// Format formats the node.
func (node PartitionBy) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Partition represents an partitions expression.
type Partition struct {
	Expr Expr
}

// Format formats the node.
func (node *Partition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Limit represents a LIMIT clause.
type Limit struct {
	Offset, Rowcount Expr
}

// Format formats the node.
func (node *Limit) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Values represents a VALUES clause.
type Values []ValTuple

// Format formats the node.
func (node Values) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// UpdateExprs represents a list of update expressions.
type UpdateExprs []*UpdateExpr

// Format formats the node.
func (node UpdateExprs) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// UpdateExpr represents an update expression.
type UpdateExpr struct {
	Name *ColName
	Expr Expr
}

// Format formats the node.
func (node *UpdateExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SetExprs represents a list of set expressions.
type SetExprs []*SetExpr

// Format formats the node.
func (node SetExprs) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SetExpr represents a set expression.
type SetExpr struct {
	Name Ident
	Expr Expr
}

// Format formats the node.
func (node *SetExpr) Format(buf *nodeBuffer) {
	_ = "STUB: not implemented"
	// We don't have to backtick set variable names.
	return
}

// OnDup represents an ON DUPLICATE KEY clause.
type OnDup UpdateExprs

// Format formats the node.
func (node OnDup) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SuffixExpr represents Suffix operator like a 'OUTPUT'.
type SuffixExpr struct {
	Expr   Expr
	Suffix string
}

// Format formats the node.
func (node *SuffixExpr) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type DeclareType int

const (
	declareVariable DeclareType = iota
	declareCursor
	declareHandler
)

type Declare struct {
	Type      DeclareType
	Variables []*LocalVariable
	Cursor    *CursorDefinition
	Handler   *HandlerDefinition
}

func (node *Declare) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type LocalVariable struct {
	Name     Ident
	DataType ColumnType
}

func (node *LocalVariable) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type CursorDefinition struct {
	Name   Ident
	Scroll bool
	Select SelectStatement
}

func (node *CursorDefinition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type HandlerConditionType int

const (
	handlerConditionMysqlErrorCode HandlerConditionType = iota
	handlerConditionSqlstate
	handlerConditionSqlwarning
	handlerConditionNotFound
	handlerConditionSqlexception
	handlerConditionName
)

type HandlerCondition struct {
	Type  HandlerConditionType
	Value string
}

func (node *HandlerCondition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// SQLSTATE value must be quoted in output

type HandlerDefinition struct {
	Action     string
	Conditions []HandlerCondition
	Statement  Statement
}

func (node *HandlerDefinition) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

const (
	OpenStr       = "open"
	CloseStr      = "close"
	DeallocateStr = "deallocate"
	FetchStr      = "fetch"
)

type Cursor struct {
	Action     string
	Fetch      string
	CursorName Ident
	Into       []Ident
}

func (node *Cursor) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type BeginEnd struct {
	Statements        []Statement
	SuppressSemicolon bool
}

func (node *BeginEnd) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type While struct {
	Condition  Expr
	Statements []Statement
}

func (node *While) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

type If struct {
	Condition      Expr
	IfStatements   []Statement
	ElseStatements []Statement
	Keyword        string
}

func (node *If) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// MSSQL

// avoid adding a semicolon after the last statement

// need end and begin for else

// avoid adding a semicolon after the last statement

// Ident represents a SQL identifier with its original name and quote status.
// This is used to track whether an identifier was quoted in the source SQL,
// which affects case-sensitivity and normalization behavior.
type Ident struct {
	Name   string
	Quoted bool
}

// NewIdent creates a new Ident.
func NewIdent(name string, quoted bool) Ident { _ = "STUB: not implemented"; return *new(Ident) }

// IsEmpty returns true if the name is empty.
func (n Ident) IsEmpty() bool { _ = "STUB: not implemented"; return false }

// Format formats the node for SQL generation.
func (n Ident) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// equalString performs a case-insensitive compare with str.
func (n Ident) equalString(str string) bool { _ = "STUB: not implemented"; return false }

func formatID(buf *nodeBuffer, original string) { _ = "STUB: not implemented"; return }

type ArrayConstructor struct {
	Elements Exprs
}

func (node *ArrayConstructor) Format(buf *nodeBuffer) { _ = "STUB: not implemented"; return }

// Ignored node
type Ignore struct{}

func (*Ignore) iStatement()        { _ = "STUB: not implemented"; return }
func (*Ignore) Format(*nodeBuffer) { _ = "STUB: not implemented"; return }
